package org.akj.lingo.learn.domain.model

import org.akj.lingo.learn.domain.usecase.PhonemeHintEngine

data class PronunciationResult(
    val overallScore: Int,
    val wordScores: List<WordScore>,
    val feedback: String,
    val isFromFallback: Boolean,
    /** Phoneme-specific hints generated by PhonemeHintEngine (may be empty). */
    val phonemeHints: List<PhonemeHintEngine.PhonemeHint> = emptyList()
)

data class WordScore(
    val word: String,
    val score: Int
)
